Remove incorrect parenthesis
This was causing this error in production:

```
django.template.exceptions.TemplateSyntaxError: Could not parse the
remainder: '()' from 'h.by_string()'
```